### PR TITLE
fuse: add DaemonTimeout mount option to set request timeout.

### PR DESCRIPTION
**Pull request by presotto**
Should work on both freebsd and darwin but I haven't tested it on freebsd.

### CODE REVIEW

**Comment by tv42** [comment]
Merged with slight edits as 5ae4e59879c71c454d3b274d487893ea7b725891 -- rebase, gofmt, split out the unrelated nit.

As for this:

```
-func (createrDir) Create(ctx context.Context, req *fuse.CreateRequest, resp *fuse.CreateResponse) (fs.Node, fs.Handle, error) {
+func (c createrDir) Create(ctx context.Context, req *fuse.CreateRequest, resp *fuse.CreateResponse) (fs.Node, fs.Handle, error) {
```

Is it an official "Google Reading" of https://github.com/golang/go/wiki/CodeReviewComments#receiver-names that even receivers that are never used should be named? I've always felt having an unused variable was the uglier of the two choices, but will adjust to whatever community standard is (in a separate commit ;)

Also, I wanted to make sure you're aware of the `daemon_timeout` changes I advocated and OSXFUSE upstream implemented: https://github.com/osxfuse/osxfuse/issues/261

**Comment by presotto** [comment]
No, that named receiver was a mistake on my part .  I had added code in the
Create routine for debugging and took it out just before submitting but
forgot to take the variable name out.  I should have looked closer.  Google
uses anonymous receivers as much as anyone else.  Sorry about leaving it in.

--- about daemon_timeout ----

Just read your thread.  The timeouts for us were happening when we
writeback to or read from AWS or GCloud (immutable files with no random
read or write).  I can get around the put delay if I'm willing to always
reply with no error to the Release and then writeback lazily, though that
has other consequences.  Not much I can do about the read though. For
example, I can't even git clone the bazil/fuse repository into our file
system without getting an error somewhere along the way and the result in
the branch is often not recoverable without deleting the tree and trying
again.  Hence we use a 240 second timeout and avoid it (to some numnber or
9s).  It of course doesn't solve all problems but it makes the file system
not that much worse than a local one that can also have errors.  I guess
the justification is that 60 seconds is arbitrary and was set to avoid over
enthusiastic terminations.  I just live in a world where enthusiasm is
defined a bit differently.

Not that I think your suggested semantics with InterruptRequest are bad.
What I would really prefer is a message like "StillWorkingOnIt" where I can
respond with "give me more time" or "interrupted".  If I don't respond, you
take down the mount.  If I do, you either assume the request is done or set
a new timer.

**Comment by tv42** [comment]
Unfortunately, it's not really OSXFUSE dictating this timeout behavior, it's OS X itself (<-- this is my current understanding; I'd love to be corrected, but please deal with OSXFUSE upstream directly, my understanding comes from them). Something to do with the Mach microkernel messaging, I think? If OSXFUSE doesn't respond in time, OS X kills the whole kext.

Previous behavior was: if any FS operation takes too long, kill the whole FS.

New(current) behavior: if any FS operation takes too long, interrupt it; if it doesn't respond to interruption, I believe OSXFUSE still kills the FS, but that's a policy internal to it that could be changed to just fail the operation in the kext, instead of waiting userspace response. (It'd need to pin the request id until userspace responds.)

So, fundamentally, to the best of my understanding, there is *no way* to write a filesystem on OSX where operations take an arbitrary amount of time.

Increasing `daemon_timeout` is doable, but at some point you'll bump into the OSX limit itself. OSXFUSE caps the value at 10 minutes:

```
common/fuse_param.h:148:#define FUSE_MAX_DAEMON_TIMEOUT                 600 /* s */
```

If what you're looking for is better handling of network delays, I'd suggest using https://godoc.org/golang.org/x/net/context#WithTimeout and as an easy way to set that for every request is `WithContext` in https://godoc.org/bazil.org/fuse/fs#Config

Of course, using `daemon_timeout` still lets you keep requests alive a little longer before they have to timeout, if you really want to wait multiple minutes for a single network operation.


As far as I understand, nothing remains here that requires changes to bazil.org/fuse; please open a new issue if that's not true.

**Comment by presotto** [comment]
10 mins is more than I need. Actually 3 minutes already covers all the
delays I've ever seen from AWS and GCloud in a month of banging at them.
However, who knows what the future will bring since I have no idea how they
could possibly take that long now.  I'm glad to get an interrupt message
rather than a hangup if we push past that.

Thanks for all the help.

**Pull request closed without merging**
