### PR TITLE
Fix comment referencing HandleReadDirer

### PR DESCRIPTION
**Pull request by pwaller**
It doesn't seem to exist any more, so I've updated it to "HandleReadDirAller".

### CODE REVIEW

**Comment by pwaller** [comment]
Ping @tv42

**Comment by pwaller** [comment]
Ping @tv42. This is cluttering my personal PR list. It's very minor and still seems correct. Please accept or close.

**Comment by tv42** [comment]
I'd rather see a non-`All` variant of `ReadDir`, insted of the current kludge. It's just a little bit more work..

**Comment by pwaller** [comment]
Fair enough. This PR simply intended to update the documentation to reflect the current state of reality. I was confused when I looked for a ReadDir and couldn't find one because I was mislead by the documentation.

**Pull request closed without merging**
