### PR TITLE
Add support for volume renaming

### PR DESCRIPTION
**Pull request by swt2c**
This isn't technically enabled in the kext side yet, but it is supposed to be
enabled soon.

### CODE REVIEW

**Comment by tv42** [comment]
I'd like to see tests, which means this needs the kext first.

What's the intended behavior when working against an older kext? I guess mount option becomes a nop (will the older kext error out?). Tests should skip when running against older kext, if doable -- what does the fs client api do when a set volume name operation is attempted on a volume that doesn't support it?

For naming, `Setvolname` is not a single word (and yes, I know existing names make the same mistake; they're legacy api that's painful to change). And I think we should spell it out, `SetVolumeName`.

The mount option could use a better name too, but I don't have a concrete idea at this time. Why is it even a mount option?

**Comment by swt2c** [comment]
> I'd like to see tests, which means this needs the kext first.

The kext change is as simple as uncommenting the lines here:
https://github.com/osxfuse/kext/blob/master/osxfuse/fuse_vfsops.c#L876
Benjamin wants to enable support in libfuse first though.

> What's the intended behavior when working against an older kext? I guess mount option becomes a nop (will the older kext error out?). Tests should skip when running against older kext, if doable -- what does the fs client api do when a set volume name operation is attempted on a volume that doesn't support it?

The intended behavior is that changing the volume name will not be supported on older kexts.  As it is currently, the kext does not check the SETVOLNAME bit, so setting it should just do nothing.

As far as what happens when trying to change a volume name on a volume that doesn't allow it - the only ways I've found to do so is with Finder and by calling DiskArbitration APIs.  In the case of Finder, Finder itself simply doesn't allow you to change the volume name.  I haven't tried with the DiskArbitration APIs.

> For naming, Setvolname is not a single word (and yes, I know existing names make the same mistake; they're legacy api that's painful to change). And I think we should spell it out, SetVolumeName.

I was only trying to match existing API's.  :-)  Would you want to rename everything? FSSetvolnamer, SetvolnameRequest, opSetvolname?

> The mount option could use a better name too, but I don't have a concrete idea at this time. Why is it even a mount option?

Because it allows you to enable and disable setting the volume name.  Again, I was just trying to match the existing code here.  Maybe EnableSetVolumeName() would be better?

**Comment by swt2c** [comment]
The kext change has been merged.  See https://github.com/osxfuse/kext/commit/cb93b95da57b7c888eb8bde681cb0c2c5c16514f

**Comment by tv42** [comment]
macOS support has been removed. If somebody wants to pick up maintaining an open source macOS FUSE, or wants to fund supporting the proprietary continuation of OSXFUSE, please get in touch.
https://github.com/bazil/fuse/issues/224

**Pull request closed without merging**
