### PR TITLE
Jschiller/fix minfs pants

### PR DESCRIPTION
**Pull request by jasonbs10**

### CODE REVIEW

**Comment by tv42** [comment]
What happened here?-)

**Comment by jasonbs10** [comment]
User error happened - github defaults to your repo every time I create a pull request :/
Btw, we're doing a high performance rewrite and debated whether we should be API compatible with upstream but decided against it as the changes were too pervasive.

**Comment by tv42** [comment]
I saw some of those changes. We should have a chat. I feel you're fixing little nits and missing the bigger things like https://github.com/bazil/fuse/issues/35 -- with `vmsplice` buffer management would look completely different.

**Comment by jasonbs10** [comment]
The only important change in all of this is reducing the amount of allocation, and you're right everything else is basically nits. We're focusing on other code right now, after which we plan to scope out if we'll use fuse or our own vfs. Vmsplice is of interest though and I'll DM you if/when we decide to make more perf changes. Are you hoping for a PR or do you have this work planned out already?

**Comment by tv42** [comment]
Well, I have a rough idea of how to use `vmsplice` right, but there's a bunch of things I *could* be doing. All help is appreciated, but talking about it first improves chances of me liking any submissions ;)

With vmsplice, there will be practically no "buffer management" allocations anymore, just a pool of large regions with multiple messages packed in each, to be reused after a refcount drops to zero.

Oh and I like what you did with avoiding the type switch, I might migrate to that too.

**Pull request closed without merging**
