### PR TITLE
Replace golang.org/x/net/context with net/context

### LINKED ISSUE #173: Use internal 'context' package
Hi,

would you merge a PR that uses the internal `context` package (which exists since Go1.7)? I'd like to drop the dependency on the old `golang.org/x/net/context` package in [restic](https://github.com/restic/restic).

Cheers,
Alex

### PR DESCRIPTION
**Pull request by fd0**
Closes #173

### CODE REVIEW

**Comment by omani** [comment]
+1

please consider to move to net/context

**Comment by fd0** [comment]
So,, is there anything else to do here?

**Comment by tv42** [comment]
Since x/net/context used type aliases, this was cosmetic only. Anyway, fixed in  03a588ad6748a69199914890f5e166508b8df3cb.

**Comment by fd0** [comment]
Great, thanks!

**Pull request closed without merging**
