### PR TITLE
Stop over-allocating receive buffers for large writes

### PR DESCRIPTION
**Pull request by damz**
This is a straight rebase of #106 by @jacobsa.

### CODE REVIEW

**Comment by kahing** [comment]
:+1: in a testcase I get ~30% speedup with this patch

**Comment by damz** [comment]
@tv42 Can we get a yay/nay?

**Comment by tv42** [comment]
Trying to find enough time.. trust me this is not forgotten.

**Comment by damz** [comment]
@tv42 I can related. No problem.

**Comment by peter-edge** [comment]
Super +1, also related to https://github.com/bazil/fuse/pull/120 haha.

**Comment by dturner-tw** [comment]
On #106 (the original version of this patch), @tv42 commented "Bumping that to 16MB improved OSX performance hugely"

I assume that this only affects performance on large write operations.  If that's so, I have a slightly different idea for solving this problem: allocate 16MB buffers, but copy small requests into new small buffers.  Most requests will be under (say) 512 bytes, so the copying won't be too expensive. And it will save about 99% of the space.  This works particularly well for "forget storms" that Linux sometimes sends.  @tv42 would that be more likely to be merged?  If so, I'll post it.

**Comment by peter-edge** [comment]
If you're really feeling ambitious, you could do a full-on segregated list version, and over time, benchmarks could tune the size of the buckets heh.

**Comment by damz** [comment]
The big question is: do we really, really need to read every request in one go? Is there really no way to read the header first and then read the body of the request?

Public documentation on the semantics of the fuse device is sparse.

**Comment by tv42** [comment]
@damz: Yes, the kernel interface (at this point) is one `read(2)` is one message; there are no length prefixes in the data.

As for everyone concerned with performance, the real fix (for Linux) is vmsplice: https://github.com/bazil/fuse/issues/35

**Comment by damz** [comment]
@tv42 I guess you mean [`splice(2)`](http://man7.org/linux/man-pages/man2/splice.2.html)? Well, for linux it is a bit moot, if it only supports a maximum of 128 kB writes anyway.

**Comment by dturner-tw** [comment]
Yes, we need to read every request in one go.  At least that's my read of the Linux kernel code and of the MacFuse code which appears to be a direct port of the Linux stuff.

**Comment by dturner-tw** [comment]
(On the other hand, if we issue a too-small read, we just get EIO and can try again with a larger buffer)

**Comment by peter-edge** [comment]
This might be extremely naive, so feel free to yell at me (I'm just looking at https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/fuse.h etc now), but if the header has a defined size, or a min/max size, even if it means Conn.rio lock is locked a tiny bit longer, could you not do `syscall.Read` for this size of the header, and then do a subsequent read afterwards?

**Comment by peter-edge** [comment]
The header at least appears to be a defined size, so that's nice, but that last comment might still be nonsense.

**Comment by dturner-tw** [comment]
@peter-edge If I understand you correctly, you're proposing reading the header first, then the rest of the message.  Unfortunately, that won't work, because of the somewhat unusual way that fuse works.  Fuse has the weird rule that you have to read a whole request (header+body) in one read() syscall.  If you try to read just the header (or anything short of the whole thing) you'll get EIO.

**Comment by peter-edge** [comment]
Heh I just learned that, was reading more...commented too soon.

So that's annoying.

**Comment by tv42** [comment]
@dturner-tw:

> This works particularly well for "forget storms" that Linux sometimes sends

Two answers for that:

- https://github.com/bazil/fuse/issues/35
- `BATCH_FORGET` in FUSE protocol version 7.16

**Comment by tv42** [comment]
Dug through the history. The reasoning for the 16MB `maxWrite` value was that OSXFUSE crapped out without it! I misremembered that as performance -- though I think it *did* help that too. See https://github.com/bazil/fuse/issues/42

I'll push something that sorts this out Very Soon Now(tm).

**Comment by tv42** [comment]
This should solved by 9e8e65293a037ce998ba0df102710c49313aa513. Had to jump through hoops to avoid OSXFUSE bugs, so ended up using my own commits with more of the reasoning written down.

**Pull request closed without merging**
