### PR TITLE
options: introduce NoBrowse option for OSX

### PR DESCRIPTION
**Pull request by strib**
https://github.com/osxfuse/osxfuse/wiki/Mount-options#nobrowse

### CODE REVIEW

**Comment by tv42** [comment]
Heads up: the future of macOS support is in danger. If you care about FUSE on macOS, please encourage talented developers to pick up maintenance of the open source project. See https://github.com/bazil/fuse/issues/224

**Comment by strib** [comment]
Thanks @tv42 we are very well aware.

Would still love to see this merged!

**Comment by tv42** [comment]
I'm working through the backlog.

@strib Do you guys have a plan for future? (Beyond being one of the commercial licencors.) Feel free to reach me off-Github to chat.

**Comment by tv42** [comment]
Rebased and merged as 3a99aca11732d514d92d69035a3751d07833b4a2

**Pull request closed without merging**
