### PR TITLE
Add go.mod and go.sum files to support Go modules.

### PR DESCRIPTION
**Pull request by creachadair**
This commit does not introduce any functional changes; it only adds the basic
configuration files needed for modules compatibility.

See also: https://github.com/golang/go/wiki/Modules

### CODE REVIEW

**Comment by creachadair** [comment]
Hi, @tv42, can you please take a look when you have a moment? Or if you can recommend someone else who should review instead, I'd be grateful for a suggestion. Thanks!

**Comment by tv42** [comment]
It's a trivial change and not needed for you to import the packages into your module-using project. There's no immediate benefit, and much larger changes still cooking. Deferring.

**Comment by creachadair** [comment]
The short-term benefit is small, but so too is the cost—and if larger changes are coming, it's better to add these files in a trivial way now. It's certainly not urgent, but doesn't block anything.

**Comment by creachadair** [comment]
> It's a trivial change and not needed for you to import the packages into your module-using project. There's no immediate benefit, and much larger changes still cooking. Deferring.

On the subject of larger changes, is there somewhere I could follow discussion about what is expected to change? I looked through the issues and didn't find anything, is there a mailing list or chat channel or something like that? I'm happy to chip in some help if that's useful, too.

**Pull request closed without merging**
